新增 NHDK Ten Point Round
goodjack/awesome-cs-training pull request #11
Opened 2022-03-18 02:08 UTC by Koyingtw

2022-03-18 04:13 UTC, rexwu1104 commented
喔~~ Koying

2022-03-18 04:48 UTC, Koyingtw commented
> 喔~~ Koying

XDD 最近正在出 4/2 的比賽，突然想到這裡還沒加

2022-03-19 13:53 UTC, goodjack requested changes

2022-03-19 13:53 UTC, goodjack commented on README.md
> + - [NHDK Discord Server](https://discord.gg/kmKvRBjgKF)
前面少一個空格，層級跑版了哦
再麻煩幫我修一下 🙏

2022-03-20 01:59 UTC, Koyingtw reviewed
已修正

2022-04-15 06:27 UTC, merged