加各式各樣的東西
goodjack/awesome-cs-training pull request #7
Opened 2021-07-28 01:33 UTC by SiriusKoan

1. fix TOC bug
2. 加入 Python 資源
3. 加入更多工具、社群、研討會

2021-07-31 15:10 UTC, goodjack commented
嗨嗨，感謝你的貢獻！

由於這個 PR 混合了很多不同的東西
可以幫我分成幾個不同的 PR 分次提交嗎
比較方便討論與聚焦

謝謝你 🙏

2021-08-01 02:18 UTC, SiriusKoan commented
好的，我重新 commit & push 了，再麻煩你 review 了~

2021-08-01 12:23 UTC, goodjack requested changes

2021-08-01 12:23 UTC, goodjack commented on README.md
> +- [**codepen**](https://codepen.io/) - 線上前端寫 Code 平台
麻煩幫我改成官方正確的寫法「CodePen」

然後想跟你討論，你覺得 CodePen 可以在哪些方面跟培訓主題連結呢

2021-08-01 12:23 UTC, goodjack commented on README.md
> +
我個人覺得以培訓資源這個主題來說
推薦一套 Git GUI 應該就很足夠了 🤔

2021-08-01 12:23 UTC, goodjack commented on README.md
> +  - [完整功能介紹](https://hackmd.io/features-tw?view)
這個很棒！感謝補充 👏
然後我發現有 [使用教學](https://hackmd.io/s/tutorials-tw) 這個書本模式
改成這個你覺得如何？

2021-08-01 12:23 UTC, goodjack commented on README.md
> +  - [HackMD chrome 擴充套件](https://chrome.google.com/webstore/detail/hackmd-it/cnephjboabhkldgfpdokefccdofncdjh)
這個也很棒 👏👏
麻煩幫我改成官方正確的寫法「Chrome 擴充功能」

2021-08-01 12:27 UTC, goodjack commented
另外特別感謝你用心貢獻
找到 TOC bug 真的超細心的 🙏

之前其他像是 Python 資源和提問的智慧都很棒！
再麻煩你整理成額外兩個 PR，可以搭配 git branch 來處理
期待你的提交，謝謝 🥰

2021-08-01 14:56 UTC, SiriusKoan commented on README.md
> +- [**codepen**](https://codepen.io/) - 線上前端寫 Code 平台
沒問題，這是我的疏漏
我覺得他跟「成為工程師」有一定的關聯性。因為在這裡沒有一個給網頁或是網頁前端的教材區塊 (不像 C++、演算法等等)，所以除了這項之外我自己覺得這裡不太有其他主題可以連結

2021-08-01 14:58 UTC, SiriusKoan commented on README.md
> +
合理合理，而且上面的 [為你自己學 Git](https://gitbook.tw/) 也有用到 SourceTree，所以感覺真的不太必要了

2021-08-01 14:58 UTC, SiriusKoan commented on README.md
> +  - [HackMD chrome 擴充套件](https://chrome.google.com/webstore/detail/hackmd-it/cnephjboabhkldgfpdokefccdofncdjh)
沒問題👌
感謝更正

2021-08-01 14:59 UTC, SiriusKoan commented on README.md
> +  - [完整功能介紹](https://hackmd.io/features-tw?view)
看起來的確比較好，感謝提醒~

2021-08-01 15:02 UTC, SiriusKoan commented
能為社群貢獻是我的榮幸 ><
也感謝你的 review，我會繼續整理然後 PR 的~

2021-08-01 16:35 UTC, goodjack commented
感謝你的協助 🎉

2021-08-01 16:35 UTC, merged

2021-08-01 16:45 UTC, goodjack reviewed
感謝你的協助 🎉